<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Acelaya\QrCode\Service\QrCodeServiceInterface'             => __DIR__ . '/src/Service/QrCodeServiceInterface.php',
  'Acelaya\QrCode\Service\QrCodeServiceAwareTrait'            => __DIR__ . '/src/Service/QrCodeServiceAwareTrait.php',
  'Acelaya\QrCode\Service\QrCodeService'                      => __DIR__ . '/src/Service/QrCodeService.php',
  'Acelaya\QrCode\Service\QrCodeServiceAwareInterface'        => __DIR__ . '/src/Service/QrCodeServiceAwareInterface.php',
  'Acelaya\QrCode\View\Helper\Factory\QrCodeHelperFactory'    => __DIR__ . '/src/View/Helper/Factory/QrCodeHelperFactory.php',
  'Acelaya\QrCode\View\Helper\QrCodeHelper'                   => __DIR__ . '/src/View/Helper/QrCodeHelper.php',
  'Acelaya\QrCode\View\Helper\QrCodeHelperInterface'          => __DIR__ . '/src/View/Helper/QrCodeHelperInterface.php',
  'Acelaya\QrCode\Module'                                     => __DIR__ . '/src/Module.php',
  'Acelaya\QrCode\Controller\Factory\QrCodeControllerFactory' => __DIR__ . '/src/Controller/Factory/QrCodeControllerFactory.php',
  'Acelaya\QrCode\Controller\QrCodeController'                => __DIR__ . '/src/Controller/QrCodeController.php',
  'Acelaya\QrCode\Exception\InvalidExtensionException'        => __DIR__ . '/src/Exception/InvalidExtensionException.php',
);
